on:
  pull_request:
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/rector.yml'
      - 'composer.json'
      - 'rector.php'

  push:
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/rector.yml'
      - 'composer.json'
      - 'rector.php'

name: rector

jobs:
  rector:
    name: PHP 8.3-ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo, pdo_pgsql
          tools: composer:v2
          coverage: none

      - name: Determine composer cache directory on Linux
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with composer
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php8.3-composer-

      - name: Update composer
        run: composer self-update

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - run: vendor/bin/rector process --ansi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply Rector changes (CI)"
          file_pattern: '*.php'
          disable_globbing: true
